"""Initial migration

Revision ID: cfb4b2e103c0
Revises: 4c219ec3d105
Create Date: 2025-11-25 19:09:50.513797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb4b2e103c0'
down_revision = '4c219ec3d105'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

